export { UbicacionCard } from './components/UbicacionCard'
export { UbicacionForm } from './components/UbicacionForm'
export { UbicacionesPage } from './pages/UbicacionesPage'
export { CreateUbicacionPage } from './pages/CreateUbicacionPage'
export { EditUbicacionPage } from './pages/EditUbicacionPage'
